from __future__ import annotations

from niri_pypc import NiriClient, NiriConnectionBundle
from niri_pypc.types.base import UnknownEvent
from niri_pypc.types.generated.event import (
    ConfigLoadedEvent,
    EventValue,
    KeyboardLayoutsChangedEvent,
    KeyboardLayoutSwitchedEvent,
    OverviewOpenedOrClosedEvent,
    ScreenshotCapturedEvent,
    WindowClosedEvent,
    WindowFocusChangedEvent,
    WindowFocusTimestampChangedEvent,
    WindowLayoutsChangedEvent,
    WindowOpenedOrChangedEvent,
    WindowsChangedEvent,
    WindowUrgencyChangedEvent,
    WorkspaceActivatedEvent,
    WorkspaceActiveWindowChangedEvent,
    WorkspacesChangedEvent,
    WorkspaceUrgencyChangedEvent,
)
from niri_pypc.types.generated.models import (
    KeyboardLayouts,
    LogicalOutput,
    Mode,
    Output,
    Overview,
    Timestamp,
    Window,
    WindowLayout,
    Workspace,
)
from niri_pypc.types.generated.reply import (
    FocusedOutputResponse,
    FocusedWindowResponse,
    KeyboardLayoutsResponse,
    OutputsResponse,
    OverviewStateResponse,
    VersionResponse,
    WindowsResponse,
    WorkspacesResponse,
)
from niri_pypc.types.generated.request import (
    FocusedOutputRequest,
    FocusedWindowRequest,
    KeyboardLayoutsRequest,
    OutputsRequest,
    OverviewStateRequest,
    VersionRequest,
    WindowsRequest,
    WorkspacesRequest,
)

__all__ = [
    "ConfigLoadedEvent",
    "EventValue",
    "FocusedOutputRequest",
    "FocusedOutputResponse",
    "FocusedWindowRequest",
    "FocusedWindowResponse",
    "KeyboardLayouts",
    "LogicalOutput",
    "Mode",
    "KeyboardLayoutsChangedEvent",
    "KeyboardLayoutSwitchedEvent",
    "KeyboardLayoutsRequest",
    "KeyboardLayoutsResponse",
    "NiriClient",
    "NiriConnectionBundle",
    "Output",
    "OutputsRequest",
    "OutputsResponse",
    "Overview",
    "OverviewOpenedOrClosedEvent",
    "OverviewStateRequest",
    "OverviewStateResponse",
    "ScreenshotCapturedEvent",
    "Timestamp",
    "UnknownEvent",
    "VersionRequest",
    "VersionResponse",
    "Window",
    "WindowLayout",
    "WindowClosedEvent",
    "WindowFocusChangedEvent",
    "WindowFocusTimestampChangedEvent",
    "WindowLayoutsChangedEvent",
    "WindowOpenedOrChangedEvent",
    "WindowsChangedEvent",
    "WindowsRequest",
    "WindowsResponse",
    "WindowUrgencyChangedEvent",
    "Workspace",
    "WorkspaceActivatedEvent",
    "WorkspaceActiveWindowChangedEvent",
    "WorkspacesChangedEvent",
    "WorkspacesRequest",
    "WorkspacesResponse",
    "WorkspaceUrgencyChangedEvent",
]
